# Static configurations for web application
web:
    port: 3000
    apiBaseRoute: "/api/v1"

# Static configurations for API application
api:
    port: 8000
    grpcPort: 8001

# Static configurations for Builder application
builder:
    grpcPort: 8002
    tempDir: "/tmp/forge-builder"
    defaultQueueOptions:
        name: "forge-builder"
        defaultJobOptions:
            attempts: 2
            backoff: 3000
    workerCount: 2

# Static configurations for Deployer application
deployer:
    grpcPort: 8003
    clusterName: "forge-cluster"
